# Installation

In [1]:
!pip install gymnasium

In [2]:
!pip install stable-baselines3[extra]

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 1.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 23.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 9.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 30.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 797.5 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 3.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 12.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 27.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.5/184.5 kB 12.9 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstall

# DQN

In [3]:
import gymnasium as gym
from stable_baselines3 import DQN

In [4]:
env = gym.make('CartPole-v1', render_mode='rgb_array')

In [5]:
# https://stable-baselines3.readthedocs.io/en/feat-gymnasium-support/modules/dqn.html
model = DQN(policy='MlpPolicy',
            env=env,
            learning_rate=0.001,
            buffer_size=1000,
            batch_size=16,
            train_freq=(5, 'episode'),
            target_update_interval=10,
            exploration_initial_eps=0.9,
            exploration_final_eps=0.1,
            exploration_fraction=0.05,
            device='cpu',
            verbose=1)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [6]:
model

In [7]:
model.learn(total_timesteps=10000, log_interval=10)

----------------------------------
| rollout/            |          |
|    ep_len_mean      | 15.8     |
|    ep_rew_mean      | 15.8     |
|    exploration_rate | 0.647    |
| time/               |          |
|    episodes         | 10       |
|    fps              | 1168     |
|    time_elapsed     | 0        |
|    total_timesteps  | 158      |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean      | 14.8     |
|    ep_rew_mean      | 14.8     |
|    exploration_rate | 0.428    |
| time/               |          |
|    episodes         | 20       |
|    fps              | 920      |
|    time_elapsed     | 0        |
|    total_timesteps  | 295      |
| train/              |          |
|    learning_rate    | 0.001    |
|    loss             | 0.535    |
|    n_updates        | 2        |
----------------------------------
----------------------------------
| rollout/            |          |
|    ep_len_mean    

In [8]:
state, _ = env.reset()

In [9]:
state

array([-0.03924289, -0.03409402,  0.03738723,  0.01763499], dtype=float32)

In [11]:
model.predict(state, deterministic=True)

(array(1), None)

In [12]:
action, _ = model.predict(state, deterministic=True)

In [13]:
action

array(1)

In [14]:
next_state, reward, done, _, _ = env.step(action)

In [15]:
next_state

array([-0.03992477,  0.16047236,  0.03773993, -0.26302135], dtype=float32)

In [16]:
reward

1.0

# DDPG

In [17]:
import numpy as np
import gymnasium as gym
from stable_baselines3 import DDPG
from stable_baselines3.common.noise import OrnsteinUhlenbeckActionNoise

In [18]:
env = gym.make('Pendulum-v1', render_mode='rgb_array')

In [19]:
n_actions = env.action_space.shape[-1]
noise = OrnsteinUhlenbeckActionNoise(mean=np.zeros(n_actions), sigma=0.1 * np.ones(n_actions))

In [20]:
# https://stable-baselines3.readthedocs.io/en/feat-gymnasium-support/modules/ddpg.html
model = DDPG(policy='MlpPolicy',
             env=env,
             learning_rate=0.001,
             buffer_size=1000,
             batch_size=16,
             train_freq=(5, 'episode'),
             action_noise=noise,
             device='cpu',
             verbose=1)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [21]:
model.learn(total_timesteps=10000, log_interval=10)

----------------------------------
| rollout/           |           |
|    ep_len_mean     | 200       |
|    ep_rew_mean     | -1.49e+03 |
| time/              |           |
|    episodes        | 10        |
|    fps             | 1496      |
|    time_elapsed    | 1         |
|    total_timesteps | 2000      |
| train/             |           |
|    actor_loss      | 0.756     |
|    critic_loss     | 83.1      |
|    learning_rate   | 0.001     |
|    n_updates       | 1         |
----------------------------------
----------------------------------
| rollout/           |           |
|    ep_len_mean     | 200       |
|    ep_rew_mean     | -1.49e+03 |
| time/              |           |
|    episodes        | 20        |
|    fps             | 1376      |
|    time_elapsed    | 2         |
|    total_timesteps | 4000      |
| train/             |           |
|    actor_loss      | 4.23      |
|    critic_loss     | 34.4      |
|    learning_rate   | 0.001     |
|    n_updates      

In [22]:
state, _ = env.reset()

In [23]:
state

array([ 0.9704954 ,  0.24111953, -0.72964835], dtype=float32)

In [24]:
action, _ = model.predict(state, deterministic=False)

In [25]:
action

array([-1.0837885], dtype=float32)

In [26]:
next_state, reward, done, _, _ = env.step(action)

In [27]:
next_state

array([ 0.97845614,  0.20645489, -0.71137697], dtype=float32)

In [28]:
reward

np.float64(-0.11371489297256246)